import { StyleSheet } from "react-native";

export const ClassReservationStyles = StyleSheet.create({
  card: {
    backgroundColor: "#1f2937",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 4,
  },
  cardValidated: {
    backgroundColor: "#1f2937",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#10b981",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#10b981",
  },
  cardExpired: {
    backgroundColor: "#1f2937",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
    opacity: 0.6,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#374151",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  headerInfo: {
    flex: 1,
  },
  className: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 4,
  },
  classInstructor: {
    fontSize: 12,
    color: "#9ca3af",
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#ffffff",
    textTransform: "uppercase",
  },
  details: {
    marginBottom: 16,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  detailText: {
    fontSize: 14,
    color: "#d1d5db",
    marginLeft: 12,
    flex: 1,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#374151",
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  priceLabel: {
    fontSize: 14,
    color: "#9ca3af",
    marginRight: 8,
  },
  priceAmount: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#e1dd2a",
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: "#374151",
    borderRadius: 8,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#e1dd2a",
    marginRight: 4,
  },
  qrContainer: {
    justifyContent: "center",
    alignItems: "center",
  },
  qrLabel: {
    fontSize: 12,
    color: "#9ca3af",
    marginTop: 8,
  },
  expiredBadge: {
    flexDirection: "row",
    alignItems: "center",
  },
  expiredText: {
    fontSize: 14,
    color: "#9ca3af",
    marginLeft: 8,
  },
  columnContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  column30: {
    width: "30%",
    justifyContent: "space-between",
    alignItems: "center",
  },
  column50: {
    width: "45%",
    justifyContent: "space-between",
  },
  column20: {
    width: "25%",
    alignItems: "center",
    justifyContent: "space-between",
  },
  verticalLine: {
    width: 2,
    height: "100%",
    backgroundColor: "#e1dd2a",
    marginHorizontal: 10,
  },
  row: {
    flexDirection: "row",
    marginBottom: 10,
    alignItems: "center",
  },
  cardTextTitle: {
    fontSize: 14,
    color: "#e1dd2a",
    fontWeight: "900",
  },
  cardTextTitleNumber: {
    fontSize: 20,
    color: "#e1dd2a",
    fontWeight: "900",
  },
  cardText: {
    fontSize: 14,
    color: "#d1d5db",
  },
  cardTextValue: {
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "600",
    marginLeft: 4,
  },
  image: {
    width: 30,
    height: 30,
    resizeMode: "contain",
  },
});
