import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");
export const AddSlotModalWidth = width;

export const AddSlotModalStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.8)",
  },
  modalContainer: {
    width: width,
    maxHeight: height * 0.85,
    padding: 20,
    paddingTop: 10,
    backgroundColor: "#f5f5f5ff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    alignItems: "center",
  },
  titleContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 5,
  },
  separator: {
    width: width,
    height: 1,
    backgroundColor: "#cccccc",
    alignSelf: "center",
    marginLeft: -20,
    marginRight: -20,
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#cccccc",
    borderRadius: 2,
    marginBottom: 15,
  },
  title: {
    fontSize: 32,
    fontFamily: "Kanit-Regular",
    color: "#000000",
  },
  titleValue: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    fontFamily: "Kanit-Regular",
    color: "#000000",
  },
  titleValueCard: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
    fontFamily: "Kanit-Regular",
    alignSelf: "center",
    color: "#000000",
  },
  input: {
    width: "100%",
    padding: 10,
    borderWidth: 1,
    borderColor: "#cccccc",
    backgroundColor: "#f8f9fa",
    color: "#000000",
    borderRadius: 5,
    marginBottom: 10,
  },
  buttonContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  containerCard: {
    width: "100%",
    justifyContent: "center",
    padding: 8,
  },
  cardField: {
    height: 60,
    borderRadius: 22,
    borderColor: "#cccccc",
    borderWidth: 1,
    backgroundColor: "#f5f5f5ff",
  },
  buttonPay: {
    marginTop: 15,
    width: width * 0.8,
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: "#121212",
    borderRadius: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  buttonPayText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Kanit-Regular",
    alignSelf: "center",
  },
  buttonCancel: {
    marginTop: 10,
    width: width * 0.8,
    padding: 8,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: "#f5f5f5ff",
    borderRadius: 22,
  },
  buttonCancelText: {
    color: "#121212",
    fontSize: 12,
    fontFamily: "Kanit-Regular",
    alignSelf: "center",
  },
  loadingContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    fontFamily: "Kanit-Regular",
    color: "#000000",
  },
  timePickerButton: {
    marginTop: 10,
    padding: 10,
    backgroundColor: "#e1dd2a",
    borderRadius: 22,
    alignItems: "center",
    marginVertical: 10,
    paddingLeft: 20,
    paddingRight: 20,
  },
  timePickerButtonText: {
    color: "#000",
    fontSize: 16,
    fontFamily: "Kanit-Regular",
  },
  centeredContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
  },
  bottomContainer: {
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  priceContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 25,
  },
  priceText: {
    fontSize: 32,
    fontWeight: "bold",
    fontFamily: "Kanit-Regular",
    color: "#000000",
  },
  termsText: {
    fontSize: 12,
    fontFamily: "Kanit-Regular",
    color: "#666666",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 5,
  },
  termsLink: {
    fontSize: 12,
    fontFamily: "Kanit-Regular",
    color: "#007bff",
    textDecorationLine: "underline",
  },
});
